import {
  LoadingIcon,
  PhoneIcon,
  PhoneOutlinedIcon,
  MenuIcon,
  CloseIcon,
  LinkedinIcon,
  InstagramIcon,
  FacebookIcon,
  UserIcon,
  EmailIcon,
  HeartFilledIcon,
  HeartOutlinedIcon,
  AccessibleOutlinedIcon,
  AccessibleSolidIcon,
  AccessibilityOutlinedIcon,
  AccessibilitySolidIcon,
  AccountBankOutlinedIcon,
  AccountBankSolidIcon,
  AccountWalletOutlinedIcon,
  AccountWalletSolidIcon,
  AccountUserBoxOutlinedIcon,
  AccountUserBoxSolidIcon,
  AccountUserCircleOutlinedIcon,
  AccountUserCircleSolidIcon,
  AlphabetIcon,
  EnergyIcon,
  AlertCircleOutlinedIcon,
  AlertCircleSolidIcon,
  AlertTriangleOutlinedIcon,
  AlertTriangleSolidIcon,
  AlignCenterIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignJustifyIcon,
  ArchiveOutlinedIcon,
  ArchiveSolidIcon
} from '../icons'

const IconMapping = {
  loading: <LoadingIcon />,
  phone: <PhoneIcon />,
  phoneOutlined: <PhoneOutlinedIcon />,
  menu: <MenuIcon />,
  close: <CloseIcon />,
  linkedin: <LinkedinIcon />,
  facebook: <FacebookIcon />,
  instagram: <InstagramIcon />,
  user: <UserIcon />,
  email: <EmailIcon />,
  heartFilled: <HeartFilledIcon />,
  heartOutlined: <HeartOutlinedIcon />,
  accessibleOutlined: <AccessibleOutlinedIcon />,
  accessibleSolidIcon: <AccessibleSolidIcon />,
  accessibilityOutlined: <AccessibilityOutlinedIcon />,
  accessibilitySolid: <AccessibilitySolidIcon />,
  accountBankOutlined: <AccountBankOutlinedIcon />,
  accountBankSolid: <AccountBankSolidIcon />,
  accountWalletOutlined: <AccountWalletOutlinedIcon />,
  accountWalletSolid: <AccountWalletSolidIcon />,
  accountUserBoxOutlined: <AccountUserBoxOutlinedIcon />,
  accountUserBoxSolid: <AccountUserBoxSolidIcon />,
  accountUserCircleOutlined: <AccountUserCircleOutlinedIcon />,
  accountUserCircleSolid: <AccountUserCircleSolidIcon />,
  alphabet: <AlphabetIcon />,
  energy: <EnergyIcon />,
  alertCircleOutlined: <AlertCircleOutlinedIcon />,
  alertCircleSolid: <AlertCircleSolidIcon />,
  alertTriangleOutlined: <AlertTriangleOutlinedIcon />,
  alertTriangleSolid: <AlertTriangleSolidIcon />,
  alignCenter: <AlignCenterIcon />,
  alignLeft: <AlignLeftIcon />,
  alignRight: <AlignRightIcon />,
  alignJustify: <AlignJustifyIcon />,
  archiveOutlined: <ArchiveOutlinedIcon />,
  archiveSolid: <ArchiveSolidIcon />
}

type AvailableIcons = keyof typeof IconMapping

export { IconMapping }
export type { AvailableIcons }
